version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend   # default name, so you can omit this line
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend   # default name, optional
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
